// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVoKbZfGHail5IpoviugHLMmKXz19R94w',
    appId: '1:667866438548:web:8c07b22d473c95ebbecd81',
    messagingSenderId: '667866438548',
    projectId: 'afro-app-ee968',
    authDomain: 'afro-app-ee968.firebaseapp.com',
    storageBucket: 'afro-app-ee968.appspot.com',
    measurementId: 'G-Z3ZT0H2HNV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCR2VxL-46AVXvauMOLmbmdxBkVny59OFI',
    appId: '1:667866438548:android:4669f7b5b47ded30becd81',
    messagingSenderId: '667866438548',
    projectId: 'afro-app-ee968',
    storageBucket: 'afro-app-ee968.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsej6uGB6ikt0tuzsbOX49kJUMjYXcS44',
    appId: '1:667866438548:ios:e1dd7eed55c51e51becd81',
    messagingSenderId: '667866438548',
    projectId: 'afro-app-ee968',
    storageBucket: 'afro-app-ee968.appspot.com',
    iosBundleId: 'com.example.afroApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsej6uGB6ikt0tuzsbOX49kJUMjYXcS44',
    appId: '1:667866438548:ios:7554a62464a9bf41becd81',
    messagingSenderId: '667866438548',
    projectId: 'afro-app-ee968',
    storageBucket: 'afro-app-ee968.appspot.com',
    iosBundleId: 'com.example.afroApp.RunnerTests',
  );
}
