# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Lane for android app firebase distribution"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --release --target lib/main.dart --no-tree-shake-icons" 
    firebase_app_distribution(
      app: "1:667866438548:android:4669f7b5b47ded30becd81",
      firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
      android_artifact_type: "APK",
      android_artifact_path: "../build/app/outputs/flutter-apk/app-release.apk",
      testers: "hadeerosama883@gmail.com",
      release_notes: "first fastlane firebase distribution",
      # groups: "qa-team, trusted-testers",
      
  )

    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
